export const LINKS = {
  HOME: "/",
  ADMIN: "/admin",
  ADMIN_CONFIGURACOES: "/admin/configuracoes",
  ADMIN_PRODUTOS: "/admin/produtos",
  ADMIN_PEDIDOS: "/admin/pedidos",
  ADMIN_CATEGORIAS: "/admin/categorias",
  CARRINHO: "/carrinho",
  CADASTRO: "/cadastro",
  CADASTRO_COMPLETO: "/cadastro-completo",
  CHECKOUT: "/checkout",
  CONFIRMACAO: "/confirmacao",
  HISTORICO_PEDIDOS: "/historico-pedidos",
  NAO_AUTORIZADO: "/nao-autorizado",
  LOGIN: "/login",
  USUARIO_CONFIG: "/usuario",
};
